services:
  taski_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taski_db
    restart: always
    volumes:
      - taski_db_data:/var/lib/postgresql

  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"
    restart: always

  backend:
    build: ./taski_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://taski_db:5432/taski_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - taski_db
    restart: always

  frontend:
    build: ./taski_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./taski_frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  taski_db_data:
    driver: local
